s= set()

n= int(input("enter first number "))
s.add(int(n))
n= int(input("enter second number "))
s.add(int(n))
n= int(input("enter third number "))
s.add(int(n))
n=  int(input("enter fourth number "))
s.add(int(n))
n= int(input("enter fifth number "))
s.add(int(n))
n= int(input("enter sixth number "))
s.add(int(n))
n= int(input("enter seventh number "))
s.add(int(n))
n= int(input("enter eighth number "))
s.add(int(n))

print(s)